batch_size: 128
checkpoints_path: ./checkpoints
dataset: amigos
dataset_path: ../../datasets/amigos
device: auto
hidden_size: 512
k: 10
lr: 5.0e-05
max_epochs: 50
max_freq: 1000
min_freq: 100
model: dino
predict_ids: true
seed: 42
single_run: false
train_perc: 0.8
validation: kfold
windows_size: 1
windows_stride: 1
