batch_size: 128
checkpoints_path: ./checkpoints
dataset: amigos
dataset_path: ../../datasets/amigos
device: auto
k: 10
lr: 5.0e-05
max_epochs: 10
max_freq: 20000
min_freq: 100
model: dino
seed: 42
single_run: true
train_perc: 0.8
validation: kfold
windows_size: 1
windows_stride: 1
