batch_size: 128
checkpoints_path: ./checkpoints
dataset: deap
dataset_path: ../../datasets/deap
device: auto
hidden_size: 512
k: 10
lr: 0.001
max_epochs: 50
max_freq: 1000
min_freq: 100
model: linear
predict_ids: true
seed: 42
single_run: false
train_perc: 0.8
validation: kfold
windows_size: 2
windows_stride: 2
