dataset: deap
dataset_path: ../../datasets/deap
setting: cross_subject
seed: 42
windows_size: 1
windows_stride: 1
dont_discretize_labels: False
dont_normalize_eegs: False
validation: loso
k: 10
train_perc: 0.8
checkpoints_path: ./checkpoints