dataset: deap
dataset_path: ../../datasets/deap
setting: cross_subject
device: gpu
seed: 42
windows_size: 1
windows_stride: 1
dont_discretize_labels: False
dont_normalize_eegs: False
min_freq: 100
max_freq: 20000
validation: kfold
k: 10
train_perc: 0.8
checkpoints_path: ./checkpoints
batch_size: 128
max_epochs: 10
single_run: True