batch_size: 128
checkpoints_path: ./checkpoints
dataset: gal
dataset_path: ../../datasets/gal
device: auto
k: 10
lr: 0.001
max_epochs: 50
max_freq: 100
min_freq: 0
model: linear
predict_ids: true
seed: 42
single_run: false
train_perc: 0.8
validation: simple
windows_size: 1
windows_stride: 1
