batch_size: 128
checkpoints_path: ./checkpoints
dataset: hg
dataset_path: ../../datasets/hg
device: auto
hidden_size: 512
k: 10
lr: 0.0005
max_epochs: 30
max_freq: 100
min_freq: 0
model: linear
predict_ids: false
seed: 42
single_run: false
train_perc: 0.8
validation: loso
windows_size: 2
windows_stride: 2
