batch_size: 128
checkpoints_path: ./checkpoints
dataset: seed
dataset_path: ../../datasets/seed
device: auto
k: 10
lr: 5.0e-05
max_epochs: 10
max_freq: 100
min_freq: 0
model: dino
seed: 42
single_run: false
train_perc: 0.8
validation: kfold
windows_size: 1
windows_stride: 1
